# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import monitor_pb2 as monitor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitorCServiceStub(object):
    """──────────────────────────────────────────────
    Servicio expuesto por MonitorC
    (MonitorS actúa como cliente gRPC)
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/monitor.MonitorCService/Ping',
                request_serializer=monitor__pb2.PingRequest.SerializeToString,
                response_deserializer=monitor__pb2.PongResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/monitor.MonitorCService/GetMetrics',
                request_serializer=monitor__pb2.MetricsRequest.SerializeToString,
                response_deserializer=monitor__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/monitor.MonitorCService/Register',
                request_serializer=monitor__pb2.RegisterRequest.SerializeToString,
                response_deserializer=monitor__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/monitor.MonitorCService/Deregister',
                request_serializer=monitor__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=monitor__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/monitor.MonitorCService/GetStatus',
                request_serializer=monitor__pb2.StatusRequest.SerializeToString,
                response_deserializer=monitor__pb2.StatusResponse.FromString,
                _registered_method=True)


class MonitorCServiceServicer(object):
    """──────────────────────────────────────────────
    Servicio expuesto por MonitorC
    (MonitorS actúa como cliente gRPC)
    ──────────────────────────────────────────────

    """

    def Ping(self, request, context):
        """Verifica que la instancia sigue viva
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Retorna métricas actuales de la instancia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """La instancia se registra con el MonitorS al arrancar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """La instancia se desregistra del MonitorS al apagarse o ser eliminada
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Estado de salud resumido (usado para diagnóstico y dashboards)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=monitor__pb2.PingRequest.FromString,
                    response_serializer=monitor__pb2.PongResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=monitor__pb2.MetricsRequest.FromString,
                    response_serializer=monitor__pb2.MetricsResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=monitor__pb2.RegisterRequest.FromString,
                    response_serializer=monitor__pb2.RegisterResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=monitor__pb2.DeregisterRequest.FromString,
                    response_serializer=monitor__pb2.DeregisterResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=monitor__pb2.StatusRequest.FromString,
                    response_serializer=monitor__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.MonitorCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitor.MonitorCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorCService(object):
    """──────────────────────────────────────────────
    Servicio expuesto por MonitorC
    (MonitorS actúa como cliente gRPC)
    ──────────────────────────────────────────────

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.MonitorCService/Ping',
            monitor__pb2.PingRequest.SerializeToString,
            monitor__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.MonitorCService/GetMetrics',
            monitor__pb2.MetricsRequest.SerializeToString,
            monitor__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.MonitorCService/Register',
            monitor__pb2.RegisterRequest.SerializeToString,
            monitor__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.MonitorCService/Deregister',
            monitor__pb2.DeregisterRequest.SerializeToString,
            monitor__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.MonitorCService/GetStatus',
            monitor__pb2.StatusRequest.SerializeToString,
            monitor__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
